### ISSUE TITLE
Island Changes

### ISSUE THREAD

**Issue by ClassyTeddy** [CCDevNelson/Snap-Updates#116]
1. Make the top and Bottom KD's a single piece. 
2. Make the backing 3/4" thick
3. Add a `Side Deck Overhang` option that defaults to 3/4"
4. Fix toe kick prompts
5. Add edgebanding instructions

There might be more, but this is what I will focus on for now. We will need to take a look at how we want inserts to interact with islands, but I will look at that in the future.

**Comment by ClassyTeddy** [comment]
This is ready for testing on the `Island-Fixes` branch.

**Comment by TEDSTANDAGE** [comment]
Great start Teddy. The back/KDs/partitions/TK's all look to be exporting the correct sizes and I think the items listed above were addressed as we discussed. 

A few items for us to add to the island fixes (feel free to close this issue and create new issues if you prefer, or we can continue the island fixes here:

1. The 3/4" back does not seem to have a material attached to it in an exported XML:

![island backing material](https://user-images.githubusercontent.com/61025894/88686512-07152500-d0ac-11ea-9d34-55521d4ab563.png)

2. It looks to be exporting two sets of TKs:

![image](https://user-images.githubusercontent.com/61025894/88686606-1b592200-d0ac-11ea-8e1e-c4472d726fe0.png)

3. The toe kick endcaps correctly have the two short edges edgebanded, however the second short edge says "S3" instead of "S2":

![image](https://user-images.githubusercontent.com/61025894/88687575-4d1eb880-d0ad-11ea-9753-a8cb48422c64.png)

4. For countertop sizing, when you select that it is up to a wall, it correctly doesn't have side overhang on the side that is up against the wall when you select "granite" or "HPL" but it still puts the overhang when "melamine" is selected (the XML exports with the overhang on melamine countertops as well):

![image](https://user-images.githubusercontent.com/61025894/88687064-a508ef80-d0ac-11ea-8034-880e707161f6.png)

![image](https://user-images.githubusercontent.com/61025894/88687085-a9350d00-d0ac-11ea-88c5-85aa4eeb0176.png)

5. When melamine countertop is selected as the countertop material, the name of the countertop still says "Granite deck" even though the IDM is correct in saying the melamine color:

![image](https://user-images.githubusercontent.com/61025894/88687955-c0282f00-d0ad-11ea-8dcc-5b9180aedf89.png)

6. There is no edgebanding currently on the island melamine countertops, though it should be 3 or 4 edges every time (depending on whether it's up against a wall):

![image](https://user-images.githubusercontent.com/61025894/88688157-e51ca200-d0ad-11ea-87ec-ded06cc0a9e9.png)

**Comment by TEDSTANDAGE** [comment]
Teddy, as I think you saw earlier this morning, Riya has addressed certain countertop issues that you might utilize here as well.

**Comment by TEDSTANDAGE** [comment]
It's a little odd that there are certain TK prompts in the Island Construction prompt menu but then also the island TKs have their own TK prompts (though the TK prompts don't seem to actually have an effect on anything):

![image](https://user-images.githubusercontent.com/61025894/88704434-ead0b280-d0c2-11ea-9d74-a5bcb8d1ff4b.png)

![image](https://user-images.githubusercontent.com/61025894/88704455-f02dfd00-d0c2-11ea-98d3-5976fcb35827.png)

If you try to open up prompts on the island countertop, it just opens the island prompts--not a separate countertop set of prompts.

The TK prompt does not accurately reflect the actual width of the TK (does not take into account the 3/8" inset on each side). It would be nice if the user could adjust the width as well to make the TK flush on the outside of the partitions (they need to be flush when we apply base molding, or sometimes when we are covering a hole in the flooring, etc.). We should also have the option to extend the TK left and right to make it flush if necessary. 

The TK prompt also makes it seem like you can adjust the depth of the TK by that prompt, but it does not actually change the depth if you type in something different (the depth looks to only be controlled by the setback option in the Island Construction prompt menu, which is fine).

My suggestion would be to just have the island prompts contain the TK and Countertop prompts within the island "Construction Options". There, it should also display the overall width and depth of both the countertop and the TK. 

We also need the option for "No Countertop".

Sorry, I know this is a lot. Teddy, we can split this up into separate issues if you'd like just let me know.

**Comment by ClassyTeddy** [comment]
So the toe kick prompts showing up was actually a bug. It was completely unintentional and caused many problems, including causing it to export two sets of toe kicks, which I just fixed. This does however mean that I cannot easily display the overall width and depth of the counter top and the TK separately from the island. If you really still want it to display the overall width and depth of those items, let me know. But I will have to change a lot of things around probably.

**Comment by TEDSTANDAGE** [comment]
We don't need the overall dimensions of the TK displayed, but I think the countertop size should be displayed if possible (doesn't need to be something that can be changed, just something displaying the dimensions after taking into account overhang, etc.). In the 2D views it should be showing the CT dimensions as well, so I'm not sure where the 2D views would get the size?

**Comment by ClassyTeddy** [comment]
The 2D views is most likely getting the size of the assembly. The overhang increases the size of the counter top to make it larger than the assembly, but it does not change the size of the assembly. I just pushed a commit that fixed some more of the addressed issues above. It addresses number 1, 2, 3, 4, 5, and 6 in your above post. My fixes are ready for testing on the `Island-Fixes` Branch. I still need to add the ability to remove the counter top. I can take a look at displaying the counter tops total dimensions, but I probably cannot get it done today.

**Comment by TEDSTANDAGE** [comment]
Thank you Teddy, don't worry about displaying the countertop size right now.

As for the other fixes:

1. The backs still don't have a material attached to it when Oxford White is my material, but also when I choose other colors it is grabbing the 1/4" SKU for that color rather than the 3/4" SKU. 

2. Looks good, only one set of TKs are exporting for me now.

3. Now I'm only getting one short edge edgebanded rather than two. It was correctly edgebanding both short sides before, it was just saying S1 and S3 rather than saying S1 and S2 like it should. Let me know if that doesn't make sense.

4. This looks like it is working correctly, taking into consideration whether it is up against the wall for melamine countertop sizing.

5. It is now exporting as "Melamine Deck" which it better. Let's have it export just as "Countertop" or "Melamine Countertop".

6. This looks like it is working correctly. I am now getting edgebanding on all sides not notated as being against a wall.

A few other items to add:

7. Capping backs for islands that only have a front opening and not a back opening need to have edgebanding on the exposed sides.

8. Toe kicks for islands that only have a front opening and not a back opening need to have their depth increased so that they sit flush all the way under the capping back. The 1.5" setback only applies to the front end that has the opening:

![image](https://user-images.githubusercontent.com/61025894/88724702-cfc06b80-d0df-11ea-9b31-bf7001a758d7.png)

9. Delete the 1" thickness option for melamine countertops--it should just be a 3/4" countertop if melamine is selected.

Thanks for all your work on this Teddy

**Comment by ClassyTeddy** [comment]
All right, I think I have addressed all the above issues except for the backing not exporting correctly. That includes:

> We also need the option for "No Countertop".

> 3. Now I'm only getting one short edge edgebanded rather than two. It was correctly edgebanding both short sides before, it was just saying S1 and S3 rather than saying S1 and S2 like it should. Let me know if that doesn't make sense.

> 5. It is now exporting as "Melamine Deck" which it better. Let's have it export just as "Countertop" or "Melamine Countertop".

> 7. Capping backs for islands that only have a front opening and not a back opening need to have edgebanding on the exposed sides.

> 8. Toe kicks for islands that only have a front opening and not a back opening need to have their depth increased so that they sit flush all the way under the capping back. The 1.5" setback only applies to the front end that has the opening:

Please test on the `Island-Fixes` branch.

**Comment by TEDSTANDAGE** [comment]
I was going to go in and test this but didn't know if the recent changes would affect it--Teddy, is this branch still ready to test? Sorry I fell behind on some of this testing.

**Comment by ClassyTeddy** [comment]
It should be fine for testing. I will most likely have to merge some of the updates currently on the master branch before I create a pull request. But go ahead and test to make sure all the issues above have been addressed.

**Comment by TEDSTANDAGE** [comment]
Unable to export an XML from this branch right now. When I get on SNaP after switching to the Island-Fixes branch it says there is an update. When I try to export an XML it takes me to the SNaP Release Log and there is no XML in the project folder. 

Teddy, can you get this branch up to date with the master branch changes so I can test? I do like the prompts and all that and things look good visually in SNaP from what I see so far, but I need to test the XML export as well. Thanks

**Comment by ClassyTeddy** [comment]
I didn't see your post until just now. I'll make sure that I fix it first thing tomorrow.

**Comment by ClassyTeddy** [comment]
I think I have it ready to go. It still opens the release log, but I can get an XML with islands in it now.

**Comment by ClassyTeddy** [comment]
I just fixed it asking for an update by just merging the master. The XML still works as well.

**Comment by TEDSTANDAGE** [comment]
Tested again and it is coming together. All the components of the island are on the XML and the edgebanding looks correct on all parts. The only thing is that the KDs for openings 2, 3, etc. (all but opening 1) are being duplicated. On the following job with 3 double openings there should be 6 KD shelves exported, but the XML contains 10 (with the 2nd and 3rd openings having 4 KDs for each instead of 2 each):

![image](https://user-images.githubusercontent.com/61025894/92150836-ea6bbb80-edd4-11ea-8de6-98cd0217df9e.png)

**Comment by ClassyTeddy** [comment]
This should be good to go and ready for testing on the `Island-Fixes` branch.

**Comment by TEDSTANDAGE** [comment]
This looks good and isn't duplicating the KDs like it was before. I think this is ready to merge unless others see issues.
