### ISSUE TITLE
All backs currently exporting as 1/4" even if 3/4" is selected

### ISSUE THREAD

**Issue by TEDSTANDAGE** [CCDevNelson/Snap-Updates#133]
As the title states, I'm finding that all backing is currently exporting as 1/4" thick even if 3/4" backs are selected (including on islands and on regular openings). 3/4" backs should match the material of the rest of the closet.

I'm not sure if https://github.com/CCDevNelson/Snap-Updates/issues/76 is related to this, but perhaps?

**Comment by ClassyTeddy** [comment]
#76 isn't related I am pretty sure.

**Comment by RyanMDev** [comment]
I was able to reproduce this, and it appears that the xml is not successfully being written/over-written with 3/4" backing selected. Which may be why it appears to not change if 1/4" was selected and exported previously.  

I also see this error message in the console, warning about multiple skus found:
![mulit_sku_err](https://user-images.githubusercontent.com/6529544/89215185-059c9e80-d57d-11ea-9efd-adef42bf3395.png)

Can you confirm this is the same error you are getting?

**Comment by ClassyTeddy** [comment]
I can confirm this Ryan. I followed a bit of a trail where the line that states `Multiple SKUs found for - Material Thickness: 0.25 Color Code: 110100`. It retrieves the material thickness value by calling the `get_part_thickness` found in the `utils.py` in the `mv` folder. For some reason, instead of getting the actual 0.75" thickness, it overwrites it and gets a 0.25 thickness.

**Comment by RyanMDev** [comment]
Alright I see. Let me take a look at this.

**Comment by RyanMDev** [comment]
For those 3 skus, which is correct for 1/4" backing material?: 

`[('PM-0000087',), ('PM-0000088',), ('PM-0000089',)]`

![oxford_white_skus](https://user-images.githubusercontent.com/6529544/89217778-95dce280-d581-11ea-863e-1fa5ceb60222.png)

For the correct material, can we identify this by the 'ItemTypeCode'?

**Comment by ClassyTeddy** [comment]
For quarter inch backs for Oxford White, Cabinet Almond, Duraply White, and Duraply Almond, we use the material found at      PM-0000041, which I believe is Dura White_Almond 10200

**Comment by ClassyTeddy** [comment]
I just published a branch with a changed csv that has the proper Display Name for the material. Please use that .csv. It is on the branch `New-CSV-For-Quarter-Inch-Backs`

**Comment by RyanMDev** [comment]
There were a few issues happening here:

1) On export, the function `write_full_sized_cover_cleat` was being ran even if no cleats/cover cleats are in the product e.g. all backing is 3/4". This was causing an error preventing OPS_Export_XML from successfully completing and writing the xml.

    Fixed with commit: CCDevNelson/SNaP-Dev@d6ec1494e984c49ebc7ed8ac01fc23683f51db79

2) Static cutpart pointer thickness was causing incorrect backing part thickness when exporting xml. Backing parts were looking to cutpart pointer 'Back' for thickness which was set to a static value of 0.25". 

    Fixed with commit: CCDevNelson/SNaP-Dev@4a52f4c6ab674305c5fa30248f930d5d94a7ccec

3) `get_material_sku` could not find the correct backing material sku for 'Oxford White' because of multiple skus found on lookup. Set 1/4" backing material sku to 'PM-0000041' if the following colors are used: Oxford White, Cabinet Almond, Duraply White, and Duraply Almond

    Fixed with commit: CCDevNelson/SNaP-Dev@9f78b8ef5d1cd558ce51d33d8d92a1a6971e5b5e

**Comment by TEDSTANDAGE** [comment]
A few issues still remaining (though please note that the lag fix/push should be prioritized before these items):

- The exported name of the 1/4" white/almond material needs to be changed to "Dura Wht_Alm", I am getting Dura White_Almond 10200

- The following Oxford White material job should have two 1/4" backs (one at 17"x40.58" and one at 17"x18.94") and two 3/4" backs (one at 17"x47.36" and one at 17"x51.64"). The pieces were exported the correct size but there were issues with the materials:

(1) The XML still says all the backs are 0.25" thick, 
(2) the 3/4" 17x51.64 back exported as IDM-0 which is the 1/4" material, 
(3) the 1/4" 17x40.58 back exported as IDM-1 which is "Oxford White" with no SKU number, and 
(4) the 3/4" 17x47.36 back exported as IDM-1 which is "Oxford White" with no SKU number.

![image](https://user-images.githubusercontent.com/61025894/89309602-751b9800-d628-11ea-82ee-36c74d1be787.png)

![image](https://user-images.githubusercontent.com/61025894/89310114-21f61500-d629-11ea-9337-34f5f28bcc99.png)

![image](https://user-images.githubusercontent.com/61025894/89310126-26bac900-d629-11ea-818d-09051fcae620.png)

![image](https://user-images.githubusercontent.com/61025894/89310142-2ae6e680-d629-11ea-825e-57165a8d3e6a.png)

**Comment by TEDSTANDAGE** [comment]
Ignore my comments about prioritizing the lag fix/push--it looks like the fix was put in on Friday

**Comment by RyanMDev** [comment]
Fixed with commit: CCDevNelson/SNaP-Dev@fdc639ffdc1d952582bdb22eccf0240640dadf19

- Change 'Dura White_Almond 10200' to 'Dura wht_alm'.
- Export correct backing thicknesses
- 'Ghost' material with no sku was being caused by incorrect backing thickness.

**Comment by TEDSTANDAGE** [comment]
Looks to be exporting correctly now, thank you
