### ISSUE TITLE
Testing for 1.2.5 Release

### ISSUE THREAD

**Issue by ClassyTeddy** [CCDevNelson/Snap-Updates#330]
This issue thread will be a place for everyone to test and share any findings for all the commits made since release 1.2.4.
The branch to be testing on will be `1.2.5-Merge-Testing`

The following are a list of issues that should have fixes available for them on this branch.
* **2D Views Changes**
    * 2D Views - Plan view - Have door be a break/opening in wall rather than just dashes #233
    * 2D Views - show return wall dimensions #234
    * 2D Views: Labels Creation #295
    * 2D Views - Label BCP size #232
    * 2D Views: Flat crown #257 
    * 2D Views: Label Capping Bottoms #262
    * Dimensions of uppers when there are no lowers #300
    * 2D Labels Pre 2D Document #313
    * Plan View stating incorrect door count #301
    * Rename Room #92
    * 2D Views: Label locks (top and side) and Double Jewelry drawers #250
    * 2D Views: Don't show KDs or File Rails as dashed lines behind Drawer Fronts & Hamper faces #294
    * 2D Views: Label File Drawers #291
    * 2D Views: Annotate left and right CT overhang amount #258
    * 2D Views: Double Partition measurements not overlapping #324
    * 2D Views: Out of place line on first elevation #267
    * 2D Views: Elevations should be scaled with one another #249
    * Restrict Saving 2D Views to only .pdfs #323

* **Corner and L Shelf Changes**
    * Add drilling info for L/R Partitions of L-Shelf and Corner Cab assemblies #317
    * L-Shelves and Corner Cabinets must always have top and bottom KD and L/R Partitions #310
    * Open Door option for L-Shelves and Corner Shelves #170
    * L-Shelf and Corner Shelf mitered partition #172
    * Fix L-Shelf and Corner Shelf backing #171

* **Filler Changes**
    * Topshelf covering filler #288
    * XML Export: Fillers #271
    * Set back filler option #252
    * Fillers: Option to edge bottom edge #272

* **Misc. Changes**
    * Update SNaP Library in Support of Pricing Software #321
    * 1/4" TK Skins as an option #14
    * Door Material Not Exporting Correctly #316
    * Doors in opening with BCP: Default swing for single doors #299
    * Default cleat location in drawer stacks/hampers should be "Below" in certain situations #287
    * Drawer box depths for lateral file rails #304
    * Shelf Stacks High Shelf Count #230
    

If I could get some thorough testing on the `1.2.5-Merge-Testing` branch from @TylerStandage, @sarahhightower, @kategodfrey, and @SeanRadvan when you guys have the time that would be awesome. 

Also, if anyone notices that I missed an issue that should be in this list please let me know. I will make sure that it is merged and add it to this list.

**Comment by TylerStandage** [comment]
This is great @ClassyTeddy and @nailsonlandim, thanks for putting it together!

**Comment by TylerStandage** [comment]
See Sarah's email that I've forwarded to the group with her comments from testing. Was going to cut and paste here, but it looks like the formatting is lost.

**Comment by ClassyTeddy** [comment]
> Default cleat location in drawer stacks/hampers should be "Below" in certain situations #287 All tests appeared to show this working, eventually. But when I brought in a counter after drawers, it did not update automatically. It took me bringing in a toe kick for the update to happen.

> Shelf stack numbers do not update immediately when you change the number of shelves in the prompt. But, as I continue to work in the file they update. I’m not sure if there is a pattern as to when the updates occur, but in one instance I increased the depth of the partitions. When I did that the shelf stack number increased at the same time.

These two issues from @sarahhightower's  email seem to be relatively the same issue. For whatever reason, it appears like her instance that she was working in didn't update the scene right away when changes were made/when things were added. She had to change _another_ thing for it to actually update the scene. I am unsure as to why as I cannot replicate this issue.

> Fillers: Option to edge bottom edge #272: Did not work for me .

This is working as intended for me, both visually and in the export. When @sarahhightower does return, I will have to see what went wrong with what she was working with.

> I received error messages when I attempted to generate 2D views so I could not test any of those Github issues. Tyler, I posted in the group chat about that so I’m hoping to get help and be able to test this Friday, as I’m in training all day tomorrow.

I did see this error message as well, and pushed a fix for what is hopefully the only problem with 2D views generation. 

I do have to ask @JJanneh if he added the lines of code of 3041-3099 in the `data_closet_carcass.py` file, as I do believe the code that was causing the may be something you copied when adding filler setback, without realizing the intended purpose of what you copied. Let me know if the code looks familiar when you can.

**Comment by TylerStandage** [comment]
I'm seeing the same issue with changing the shelf stack number of shelves; number only changes in scene after changing something else afterward.

Also seeing that the hutch back is extending out to the ends of fillers instead of nestling between the outer partitions.

**Comment by JJanneh** [comment]
amount changed to .value thanks for update on the code in the data_closet_carcass.py file
**line 3052** 
x_placement = self.product.obj_bp.location.x + l_thickness.value() + left_filler_setback_amount()
**changed----> x_placement = self.product.obj_bp.location.x + l_thickness.value() + left_filler_setback_amount.value()**
![Screenshot (813)](https://user-images.githubusercontent.com/76751383/114900024-5204d300-9dc8-11eb-9376-05140d3a16ef.png)

**Comment by ClassyTeddy** [comment]
@JJanneh I already fixed the issue. I told you that. The line in question has NOTHING to do with the prompts menu. Please tell me why you copied lines 3041-3099.

**Comment by JJanneh** [comment]
@ClassyTeddy 
![2021-04-15 09_05_37-Set back filler option · Issue #252 · CCDevNelson_Snap-Updates](https://user-images.githubusercontent.com/76751383/114901766-f9363a00-9dc9-11eb-92a5-5b7d0088182f.png)

**Comment by ClassyTeddy** [comment]
J that has to do with a problem with what you put in the drivers. That is about 2000 lines up in a different class from what I am talking about.

**Comment by JJanneh** [comment]
This was a sample from the   left_filler.value() #LEFT FILLER above lines **2980-3028**

**Comment by ClassyTeddy** [comment]
So then yeah, it should be removed. You copied over code that needed to look at the width for the plan view, and wrote extra code that instead of using the value of the width of the filler, it used the filler's setback value.

**Comment by ClassyTeddy** [comment]
> I get this error when trying to load snap defaults now. I don't think it did so this morning when I loaded:

I just pushed a CCItems change that should hopefully solve this issue. I am unsure if this was causing other issues as well.

**Comment by ClassyTeddy** [comment]
> Also seeing that the hutch back is extending out to the ends of fillers instead of nestling between the outer partitions.

A fix for this is ready for testing on the `1.2.5-Merge-Testing` branch.

**Comment by JJanneh** [comment]
L/R Capping filler, L/R EdgeBottom, Add Hutch Backing Image below shows working. ![Screenshot (816)](https://user-images.githubusercontent.com/76751383/114916273-787f3a00-9dd9-11eb-9994-4d3cdb51a31e.png)
![Screenshot (815)](https://user-images.githubusercontent.com/76751383/114916363-8df46400-9dd9-11eb-9dd5-89226ba8e05e.png)

**Comment by TylerStandage** [comment]
I can't select other colors besides Oxford white for 1mm edge, drawer face, or general materials. You can see the slim black box trying to open, but there's nothing there. The countertop, stain color selections, etc look to be there, however. 

![image](https://user-images.githubusercontent.com/77167318/114934519-d5391f80-9dee-11eb-8c30-40a4daf408ad.png)

**Comment by TylerStandage** [comment]
when I click to render selected scenes in 2D view walls disappear and an error comes up.

![image](https://user-images.githubusercontent.com/77167318/114936270-0f0b2580-9df1-11eb-8b85-8c0eeb2c2374.png)

**Comment by TylerStandage** [comment]
Here's what I see after I save the 2D view and the pdf pops up. THe PDFs aren't the design I made (they're somewhat close, but have extra openings and items running of in various directions. I've added the PDF here as well. I don't think I can manipulate the design anymore at the point.  The walls turn orange when selected and I can't get the full room/other walls to show up. 

![image](https://user-images.githubusercontent.com/77167318/114936543-6d380880-9df1-11eb-8cde-dc2bab12bac5.png)

![image](https://user-images.githubusercontent.com/77167318/114936831-cdc74580-9df1-11eb-8ed1-958694117400.png)
[2D Views.pdf](https://github.com/CCDevNelson/Snap-Updates/files/6321063/2D.Views.pdf)

**Comment by RyanMDev** [comment]
> I can't select other colors besides Oxford white for 1mm edge, drawer face, or general materials. You can see the slim black box trying to open, but there's nothing there. The countertop, stain color selections, etc look to be there, however.

It is an issue with `CCItems.csv`. I have a fix for this on 2.0.

This is likely causing the other issues you are seeing. Let me apply the fix to the `1.2.5-Merge-Testing` branch.

**Comment by RyanMDev** [comment]
I am seeing this error on startup.

![ccitems-err](https://user-images.githubusercontent.com/6529544/114937780-19c6ba00-9df3-11eb-8e15-3ce4d01a12fa.png)



Are you seeing the same if you open the console window?

**Comment by CCDevNelson** [comment]
I guess I'll chime in on this one....I'm pretty sure the new csv file has ALL 1mm Tape removed from it now.
This is a change that is happing at our production side, where everything that was label "1mm" is now "1 mm Dolce". Brock can verify all of this, but I do know that those "1mm" entries have all been removed.

**Comment by RyanMDev** [comment]
Fix for importing `CCItems.csv` is available on branch: `1.2.5-Merge-Testing`.

**Comment by nailsonlandim** [comment]
Hi @TylerStandage, can you share the file involved in the 2D View/PDF Issue?

**Comment by RyanMDev** [comment]
Another thing to note here:

Whenever there is a change to `CCItems.csv`, the "Load SNaP Defaults" command needs to run to rebuild the database and reflect those changes in the UI.

**Comment by nailsonlandim** [comment]
Hi @TylerStandage 

Just fixed the errors for 2D views. remind to clean the existing 2D views and generate them again.

**Comment by TylerStandage** [comment]
OK, thanks for all the work and updates today!  I've just completed another round of testing and most of these are in place as far as I can tell.  The 2D items that I have not tested/passed off as of yet (Nailson, I think the errors I was getting earlier are user-error): 

#324: I believe that the image below shows a situation where the height of the pard on the right should be moved. @nailsonlandim let me know if I'm missing something on this:

![image](https://user-images.githubusercontent.com/77167318/114962725-172e8980-9e20-11eb-8b78-aa346d23da62.png)

 #267 / #249 : These may be good to go, but I can't recreate the situations closely enough to think I'm sure it's there. @sarahhightower can you take a look at these?

#310 : I'm able to remove L/R panels and make top or bottom shelves non-KD
#171: I think this one is good, actually, but @ClassyTeddy can you confirm the drilling is correct?  I see the drilling there, but unsure it's definitely in the right place. 

#321 : this is actually done, I believe. But want @ClassyTeddy and @RyanMDev to confirm as well.

Thanks and talk to you all tomorrow!

**Comment by ClassyTeddy** [comment]
> I'm able to remove L/R panels and make top or bottom shelves non-KD

I will look into why the L/R panels are removable. I tried to make the top/bottom KD forced as locked, but I couldn't find a way. But, I just had an idea for it that I'm going to try as well.

> @ClassyTeddy can you confirm the drilling is correct?

As far as I can tell from measurements and the debug view, it is correct.

**Comment by nailsonlandim** [comment]
> #324: I believe that the image below shows a situation where the height of the pard on the right should be moved. @nailsonlandim let me know if I'm missing something on this:
> 
> ![image](https://user-images.githubusercontent.com/77167318/114962725-172e8980-9e20-11eb-8b78-aa346d23da62.png)
> 

IM Errors

![image](https://user-images.githubusercontent.com/70038700/115035729-3fab9780-9ea3-11eb-903e-f47dfbf6d03f.png)
![image](https://user-images.githubusercontent.com/70038700/115035802-52be6780-9ea3-11eb-98c3-a074a98f9f40.png)

You're correct @TylerStandage, I've pushed fixes for that and for the errors you mentioned me on IM.

**Comment by sarahhightower** [comment]
Question on issue #304 pertaining to drawer box depths for lateral file rails. The drawer prompt/options works well for this. In my 2D there is no indication that the drawer box should be 17" with the 19" depth partitions. Not sure if that's just an export notation or if this should be on the 2D as well?

![Files](https://user-images.githubusercontent.com/72047269/115077892-a33dc100-9eb3-11eb-936e-afc1eb0b07a0.jpg)

**Comment by ClassyTeddy** [comment]
A fix for issue #310 is ready for testing on the `1.2.5-Merge-Testing` branch. Let me know if this solution will work @TylerStandage

**Comment by AntonioGloria** [comment]
I just pushed a fix for #233 to the 1.2.5-Merge-Testing branch. The double swing door icon should be drawing correctly now.

**Comment by AntonioGloria** [comment]
Hi @TylerStandage, @sarahhightower,
I have now pushed a fix for #267 to the 1.2.5-Merge-Testing branch. The extraneous ceiling height dimensions should no longer appear.

**Comment by TylerStandage** [comment]
Great thanks Antonio! Have a great weekend

**Comment by TylerStandage** [comment]
#310 looks good Teddy. 
#233 looks good to me too, Antonio. I see double doors swings now.  @sarahhightower is that what you see/expected?
On #267, I'll let Sarah test and comment on that one.
Also, I'm seeing that #262 is in place as well.  Sarah, do you agree we can check that one off? 

@nailsonlandim @AntonioGloria @ClassyTeddy, let me know what you see as still needing to finish up before we can get this version out the door. There are a few boxes not checked yet, and I know Nailson has the accordion views to add in as well (without dimensions included).

**Comment by nailsonlandim** [comment]
Hi,

Added Drawer box depths for lateral file rails on 2D views just like the example below.

![image_2021_04_19T16_09_53_791Z](https://user-images.githubusercontent.com/70038700/115269596-dd0c0300-a111-11eb-8c2f-5a075eb20d1d.png)

If you have any other questions about it just let me know.

**Comment by ClassyTeddy** [comment]
I found a bug involving the Veneer Material Type in the `Closet Materials` tab. Selecting the veneer material caused nothing else to be drawn in the tab due to an error occurring where no material was found for veneer. I found that the issue was because there were name differences between our .blend files and the display names in the database (there was an extra space). I solved the issue and it is ready for testing on the `1.2.5-Merge-Testing` branch.

**Comment by AntonioGloria** [comment]
I just pushed a fix for the dashed lines showing in the drawers. This was related to the labeling changes made in #295. This fix should also make the text of some dimensions look black again instead of like an outline.

**Comment by sarahhightower** [comment]
> #233 looks good to me too, Antonio. I see double doors swings now. @sarahhightower is that what you see/expected?

Yes, looks great!

> On #267, I'll let Sarah test and comment on that one.

I don't notice this issue in my testing. Looks good!

> Also, I'm seeing that #262 is in place as well. Sarah, do you agree we can check that one off?

Almost. The only thing I still see missing from this one is the labeling of exposed ends. The prompt has the option to note when there are exposed ends and it should function just like the top shelf does when there are exposed ends. This is with a dash to the letters "exp".  Here's what it looks like now:

![Screenshot 2021-04-19 154027](https://user-images.githubusercontent.com/72047269/115313328-e86a2900-a127-11eb-9744-f6f3b9a7a5b2.jpg)

**Comment by AntonioGloria** [comment]
Hi @TylerStandage, @sarahhightower,
I have pushed the fix for the capping bottom exposed edge labels.
![Wall B](https://user-images.githubusercontent.com/74732175/115442201-5b7ea880-a1d7-11eb-9f12-bcf3d47d5192.png)

**Comment by ClassyTeddy** [comment]
Top Shelf should now once again automatically cover filler, and the filler should now disappear and have it's values set to 0 when unselected.

**Comment by nailsonlandim** [comment]
Added Accordion Views.

I've added a checkbox on Closet 2D Setup, so the user can choose if they will be generated, and the PDF options are changed. by default the checkbox is unmarked. 

![Accordions Option](https://user-images.githubusercontent.com/70038700/115449518-4dd61c80-a1f1-11eb-8ce6-8fca2d57c103.png)

![PDF Accordion Options](https://user-images.githubusercontent.com/70038700/115449510-4adb2c00-a1f1-11eb-8e93-2ed76bb3913e.png)

![image](https://user-images.githubusercontent.com/70038700/115449594-6a725480-a1f1-11eb-9f8d-c6c6fc9f9205.png)

**Comment by nailsonlandim** [comment]
Hi, @TylerStandage and @sarahhightower,

Just pushed a fix for toe kicks

![image](https://user-images.githubusercontent.com/70038700/115585302-dc09db80-a2a1-11eb-847f-458c330e4784.png)

So if there is a Corner Shef / L-Shelf it gets the correct measure, and if there is more than one TK, it will place it with an offset, without repeating them.

**Comment by ClassyTeddy** [comment]
A fix that removed the `Shelves Only` library item is available and ready for testing on the `1.2.5-Merge-Testing` branch.

**Comment by AntonioGloria** [comment]
I have pushed a fix for the bolding effect appearing in elevations to the `1.2.5-Merge-Testing`  branch.

**Comment by nailsonlandim** [comment]
For situations where the additional pards appears it can be solved by cleaning orphan data from the blender file. to do it follow these steps:

**Go to the corner with the three angled lines, click and drag it**

![image](https://user-images.githubusercontent.com/70038700/115613728-26e81b00-a2c3-11eb-9080-42562c974f36.png)

**It will appear another canvas, go to the small select box and choose the Outliner option**

![image](https://user-images.githubusercontent.com/70038700/115614012-81817700-a2c3-11eb-8dfc-b140b5d4ae7a.png)
![image](https://user-images.githubusercontent.com/70038700/115614108-9eb64580-a2c3-11eb-8acf-e1869312b5f3.png)

**Go to the select box that says 'All Scenes' and choose 'Orphan Data'**

![image](https://user-images.githubusercontent.com/70038700/115614194-c5747c00-a2c3-11eb-84ff-6f0259fab709.png)

**And click Purge Data**

![image](https://user-images.githubusercontent.com/70038700/115614244-d6bd8880-a2c3-11eb-9213-9c74500b9743.png)

**It will show a confirmation message, click it and wait a while**

![image](https://user-images.githubusercontent.com/70038700/115614554-3b78e300-a2c4-11eb-9d25-15ffd8db593f.png)

**After it you can close the outliner by joining the area, do it with the mouse right button at the line between the 3d canvas and the outliner, click join area**

![image](https://user-images.githubusercontent.com/70038700/115614358-fc4a9200-a2c3-11eb-8ec6-b1f373cd1464.png)

**Now an arrow will appear, move the mouse right and click it, now the outline will disappear**

![image](https://user-images.githubusercontent.com/70038700/115615053-d1ad0900-a2c4-11eb-964a-aa94d4e4d352.png)

**Comment by TylerStandage** [comment]
Thanks @nailsonlandim, we'll keep this in our back pocket for an answer to questions that come up in this regard.

EVERYONE, thank you so much for all the testing, updates, new coding, trouble shooting, brain storming, and re-testing/testing one more time that you have all put in over the past couple of weeks!  From what I can tell it looks like this is ready to be sent over to Ryan to get ready for release later this evening.  I'll give another 30 minutes for anyone to make a comment, find a bug, raise an issue, etc... .If we don't have any objections by 2:05pm AZ time, @ClassyTeddy let's get the pull request prepared and sent over to Ryan!
