### ISSUE TITLE
1.2.6 hot fix required updates

### ISSUE THREAD

**Issue by TylerStandage** [CCDevNelson/Snap-Updates#332]
Need to get the following fixes in place. Will add to this if needed: 

- [ ] Labels on exposed ends are not currently showing automatically in 2D views (@AntonioGloria )
- [ ] L-shelves, the option is no longer available to remove partitions and use top shelf rather than a top KD. Franchise has asked that this be added in again (@ClassyTeddy )
- [ ] Melamine drawer box bottoms are being exported .05" too wide--those need to be the opening width minus 1" exactly (@ClassyTeddy )
- [ ] Issues Sarah found in 2D views: missing walls, repeated walls, labels offset a long way from the images, incorrect pard size labels, elevations that don't match size (@AntonioGloria )

**Comment by AntonioGloria** [comment]
I have created the branch `1.2.6-Hotfixes` and committed a fix that brings back the exposed edges labels for Top Shelves.

**Comment by AntonioGloria** [comment]
Found and fixed a bug where the hashmark for double jewelry drawers was being added with the wrong rotation
![image](https://user-images.githubusercontent.com/74732175/117321011-616cbe80-ae52-11eb-8436-ee0d29814962.png)
![image](https://user-images.githubusercontent.com/74732175/117321048-692c6300-ae52-11eb-8be2-0f2f124295d3.png)

**Comment by ClassyTeddy** [comment]
>  L-shelves, the option is no longer available to remove partitions and use top shelf rather than a top KD. Franchise has asked that this be added in again (@ClassyTeddy )

> Melamine drawer box bottoms are being exported .05" too wide--those need to be the opening width minus 1" exactly (@ClassyTeddy )

Both of these are ready for testing on the `1.2.6-Hotfixes` branch. 

I do want to say that the drawer box bottoms were deliberately being set to 0.1" wider than the opening minus 1". That was 0.5" on both sides. I am unsure as to why, but it did seem very intentional.

**Comment by AntonioGloria** [comment]
I have pushed a fix for the bug that caused L-Shelves to not appear in plan views and created extraneous return wall dimensions. It's ready for testing in the `1.2.6-Hotfixes` branch.
![image](https://user-images.githubusercontent.com/74732175/117375881-9a7a5280-ae95-11eb-832d-dea49e7e4863.png)

**Comment by AntonioGloria** [comment]
I have pushed a fix that restores L-Shelf and Corner Shelf Plan View labels to the `1.2.6-Hotfixes` branch.
![image](https://user-images.githubusercontent.com/74732175/117470293-41a1cd00-af1c-11eb-9e9f-abb3c4e7418e.png)

**Comment by sarahhightower** [comment]
Tested most issues above and things are looking good! Still seeing some issues with custom rooms that I'll converse with @AntonioGloria about.

**Comment by ClassyTeddy** [comment]
@sarahhightower I have hopefully fixed the export error. It seems that there was an error with capping bottoms that might have caused the issue. If you could export that same room on the `1.2.6-Hotfixes` branch, and see if it exports this time that would be great.

Also, @AntonioGloria, I know that you and @sarahhightower talked about an issue with custom room drawings, where it threw an error when she tried to collect the walls if I am understanding correctly, and it threw an error in the `assign_wall_material` function that is in the `__init.py__` file found in the `room_builder` folder. It looks like that there is a case where `wall.get_wall_mesh()` on line 1651 returns `None`. I cannot replicate it, but I hope that this information helps in some way. If you need more assistance let me know. 

Also, is this the last known issue we need to solve?

**Comment by AntonioGloria** [comment]
Hi @ClassyTeddy,
Thanks for the tip! I am currently working on an issue regarding the floor line on elevation views, and @nailsonlandim is helping me out with some issues regarding the cross-sections and 2D Views.

**Comment by AntonioGloria** [comment]
I have pushed the fix for the extra empty space caused by the floor on elevation views.

**Comment by TylerStandage** [comment]
@ClassyTeddy the latest version is ready for hotfix release.  I think there are still bugs to iron out in custom rooms that lead to xml's not going perfectly, and there are some improvements on the 2D views to make as well.  But the consensus is we're at a good point where we've addressed the major issues and can push forward. Thanks to @AntonioGloria @nailsonlandim @sarahhightower and @teddy for all your work on this!

**Comment by ClassyTeddy** [comment]
@TylerStandage I will start making the pull request. 

On the note of not being able to export XML's, @sarahhightower I was able to export the room that you gave me with no problems, which means that you have a setting turned on that I do not, it has nothing to do with the rooms themselves.

I think I know the setting you have on that might be making it so you cannot export. In your user preferences for the SNaP Add-On, do you have Debug Mode enabled?

**Comment by sarahhightower** [comment]
@ClassyTeddy I did not have it enabled. So I enabled it, "exported selected rooms" again, and then checked for the XML file.  I still don't see it appear in my projects folder. Below are some screenshots to show you my settings and my projects folder. Let me know if I'm missing something.

![Screenshot 2021-05-07 145650](https://user-images.githubusercontent.com/72047269/117516486-189a3000-af4e-11eb-9d9a-9f1931288260.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/72047269/117516548-4f704600-af4e-11eb-88a2-849633d39bb2.jpg)

**Comment by ClassyTeddy** [comment]
Make sure you turn debug mode off, load snap defaults, then, try and export the file again please.

**Comment by sarahhightower** [comment]
Ah, it was off before. I just turned it off again and followed your guidance above. Still no XML exporting for me after "exporting selected room".

**Comment by ClassyTeddy** [comment]
I found the problem, it looks like the logic for fillers where if a filler was less than 4" inches it would round up to 4" was applying to every single object. That, and for whatever reason someone also added 3" to cleats heights. The problem should be fixed and is ready for testing on the `1.2.6-Hotfixes` branch.

**Comment by TedCC1209** [comment]
> Also -- same job/project as above. There are two tall 16" deep partitions where should have had full drilling on the right (16" deep all the way down the 78.86" and 90.20" partitions respectively) and only 12" deep drilling halfway down the partition on the left (47.37x12" drilled on the left of the 78.86" x 16" partition and 59.96" x 12" drilled on the left of the 90.20" x 16" partition). Unfortunately it drilled all the way down on the left side of those partitions.
> 
> See the partitions that are second to the far right partition on Walls B and C, respectively:
> 
> [2D Views.pdf](https://github.com/Classy-Closets/Snap-Updates/files/6453119/2D.Views.pdf)

Note -- It properly drilled the 12" pattern from the back on the left side of those partitions, it just drilled all the way down the partition instead of stopping at 47.37" and 59.96", respectively.

**Comment by ClassyTeddy** [comment]
It seems like this was intentionally removed. @RyanMDev, why was this logic commented out in the data_closet_carcass.py file?

```python
        #panel.prompt('Stop Drilling Bottom 
        # Left','Stop_LB_Left_Opening',[Stop_LB_Left_Opening])
        # panel.prompt('Stop Drilling Top
        # Left','Start_LB_Left_Opening',[Start_LB_Left_Opening])
        # panel.prompt('Stop Drilling Bottom
        # Right','Stop_LB_Right_Opening',[Stop_LB_Right_Opening])
        # panel.prompt('Stop Drilling Top
        # Right','Start_LB_Right_Opening',[Start_LB_Right_Opening])
```

**Comment by RyanMDev** [comment]
> It seems like this was intentionally removed. @RyanMDev, why was this logic commented out in the data_closet_carcass.py file?
> 
> ```python
>         #panel.prompt('Stop Drilling Bottom 
>         # Left','Stop_LB_Left_Opening',[Stop_LB_Left_Opening])
>         # panel.prompt('Stop Drilling Top
>         # Left','Start_LB_Left_Opening',[Start_LB_Left_Opening])
>         # panel.prompt('Stop Drilling Bottom
>         # Right','Stop_LB_Right_Opening',[Stop_LB_Right_Opening])
>         # panel.prompt('Stop Drilling Top
>         # Right','Start_LB_Right_Opening',[Start_LB_Right_Opening])
> ```

Let me take a look at this.

**Comment by ClassyTeddy** [comment]
I just pushed a fix for this on the `1.2.6-Hotfixes` branch. @RyanMDev yes I did take a look at it and implemented my own logic, but I don't know if there were reasons for excluding logic like this. Let me know if the following logic sounds correct:

* If the opening to the left of a panel is less than the opening on the right side:
    * If the left opening is floored:
        * Then we start the drilling on the left side at the left side opening height and stop at the bottom
     * If the opening is not floored:
        * Then we start the drilling on the left side at the top and stop at the left side opening height

* If the opening to the right of a panel is less than the opening on the left side:
    * If the right opening is floored:
        * Then we start the drilling on the right side at the right side opening height and stop at the bottom
     * If the opening is not floored:
        * Then we start the drilling on the right side at the top and stop at the right side opening height
